require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '13.4'
prepare_react_native_project!

# LA SOLUCIÓN ARQUITECTÓNICA: Usar frameworks estáticos
# Esto permite que Swift (react-native-video) y C++ (glog) convivan en paz.
use_frameworks! :linkage => :static

target 'testCrehana' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :fabric_enabled => false,
  )

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-video', :path => '../node_modules/react-native-video'

  post_install do |installer|
    # Configuración limpia por defecto de React Native. Cero hacks.
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
  end
end